In [1]:
# Import pandas
import pandas as pd

In [2]:
# Create a DataFrame with balance.txt
df = pd.read_csv('balance.txt', sep=' ')

Write the code needed to produce a report that provides the following information:
* Compare the average income based on ethnicity.
* On average, do married or single people have a higher balance?
* What is the highest income in our dataset?
* What is the lowest income in our dataset?
* How many cards do we have recorded in our dataset? (Hint: use `sum()`)
* How many females do we have information for vs how many males? (Hint: use `count()` for a list of all methods for computation of descriptive stats, explore the [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/reference/frame.html#computations-descriptive-stats)).

In [3]:
# Compare the average income based on ethnicity
average_income_by_ethnicity = df.groupby('Ethnicity')['Income'].mean()
print("Average income based on ethnicity:")
print(average_income_by_ethnicity)

Average income based on ethnicity:
Ethnicity
African American    47.682101
Asian               44.187833
Caucasian           44.521945
Name: Income, dtype: float64

In [4]:
# On average, do married or single people have a higher balance?
average_balance_married = df[df['Married'] == 'Yes']['Balance'].mean()
average_balance_single = df[df['Married'] == 'No']['Balance'].mean()
print("\nAverage balance for married people:", average_balance_married)
print("Average balance for single people:", average_balance_single)

Average balance for married people: 13.388473477498913
Average balance for single people: 13.493509015134242

In [5]:
# What is the highest income in our dataset?
highest_income = df['Income'].max()
print("\nHighest income in the dataset:", highest_income)

Highest income in the dataset: 186.634

In [6]:
# What is the lowest income in our dataset?
lowest_income = df['Income'].min()
print("Lowest income in the dataset:", lowest_income)

Lowest income in the dataset: 10.354

In [7]:
# How many cards do we have recorded in our dataset?
total_cards = df['Cards'].sum()
print("\nTotal number of cards recorded:", total_cards)

Total number of cards recorded: 1183

In [8]:
# How many females do we have information for vs how many males?
female_count = df[df['Gender'] == 'Female'].shape[0]
male_count = df[df['Gender'] == 'Male'].shape[0]
print("Number of females:", female_count)
print("Number of males:", male_count)

Number of females: 207
Number of males: 193